### ISSUE TITLE
PermitTcpPortv4 needed

### ISSUE THREAD

**Issue by seanhaydongriffin** [HavenDV/H.Vpn#1]
Greetings,

This package is fantastic.  Though what I need is the ability to permit traffic over a TCP port.  You have the PermitUdpPortv4 method that allows UDP ports to be permitted.  I cannot see the TCP equivalent.

Looks easy to write one.  Though I am having a hard time building this solution under .Net framework 4.5.1.

**Comment by HavenDV** [comment]
Hi. Thank you for using the package and suggesting improvements. At the moment, I think the easiest way for you to offer a PR is through the github interface, it's pretty trivial. If there are any problems, the CI build will fail. If you don't have time, I can add this little later.

**Comment by HavenDV** [comment]
https://dotnet.microsoft.com/en-us/download/dotnet-framework/thank-you/net451-developer-pack-offline-installer
